<a href="https://colab.research.google.com/github/Cinaed254/Dictionary-Password-Cracker/blob/master/Copy_of_MNIST_Classification.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
# importing the necessary libraries
import tensorflow as tf
import numpy as np

In [ ]:
# importing the dataset
(X_train, y_train), (X_test, y_test) = tf.keras.datasets.mnist.load_data()

print(f"X train: {X_train.shape}")
print(f"y train: {y_train.shape}")
print(f"X test: {X_test.shape}")
print(f"y test: {y_test.shape}")

X train: (60000, 28, 28)
y train: (60000,)
X test: (10000, 28, 28)
y test: (10000,)


In [ ]:

# viewing a sample segment of data to understand its composition
print(f"X train sample: {X_train[:10]}")
print(f"X train max: {np.max(X_train)}")
print(f"y train sample: {y_train[:10]}")

X train sample: [[[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 ...

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]

 [[0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  ...
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]
  [0 0 0 ... 0 0 0]]]
X train max: 255
y train sample: [5 0 4 1 9 2 1 3 1 4]


In [ ]:
# normalize all data between 0 and 1 for faster computation based on smaller but meaningful ranges of values
X_train_norm = (X_train-np.min(X_train))/(np.max(X_train)-np.min(X_train))
X_test_norm = (X_test-np.min(X_test))/(np.max(X_test)-np.min(X_test))
print(f"X train normalized max: {np.max(X_train_norm)}")
print(f"X test normalized max: {np.max(X_test_norm)}")

X train normalized max: 1.0
X test normalized max: 1.0


In [ ]:
# now building the classifier using keras layers
model = tf.keras.models.Sequential()
model.add(tf.keras.layers.Flatten(input_shape=(28, 28)))
model.add(tf.keras.layers.Dense(128, activation="relu"))
model.add(tf.keras.layers.Dense(10))

model.summary()

Model: "sequential_1"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten (Flatten)           (None, 784)               0         
                                                                 
 dense (Dense)               (None, 128)               100480    
                                                                 
 dense_1 (Dense)             (None, 10)                1290      
                                                                 
Total params: 101770 (397.54 KB)
Trainable params: 101770 (397.54 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________


In [ ]:

# compiling the model with appropriate parameters to gauge how it is performing
model.compile(optimizer='adam',
              loss=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True),
              metrics=['accuracy'])

In [ ]:
# fitting the model onto the training data
model.fit(X_train_norm, y_train, epochs=10, verbose=1)

Epoch 1/10
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2553 - accuracy: 0.9270
Epoch 2/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.1086 - accuracy: 0.9675
Epoch 3/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0741 - accuracy: 0.9780
Epoch 4/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0558 - accuracy: 0.9830
Epoch 5/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0433 - accuracy: 0.9863
Epoch 6/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0333 - accuracy: 0.9895
Epoch 7/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0271 - accuracy: 0.9915
Epoch 8/10
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0216 - accuracy: 0.9934
Epoch 9/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.0172 - accuracy: 0.9947
Epoch 10/10
1875/1875 [==============================] - 3s 2ms/step - loss: 0.015

In [ ]:
# evaluating the new model on unseen data
test_loss, test_acc = model.evaluate(X_test_norm, y_test, verbose=1)
print(f"Test loss: {test_loss}\nTest Accuracy: {test_acc}")

313/313 [==============================] - 0s 1ms/step - loss: 0.0820 - accuracy: 0.9780
Test loss: 0.08202774077653885
Test Accuracy: 0.9779999852180481
